Table Bлюда {
	id_блюда integer [ pk increment not null unique ]
	Название text
	Калории integer
	Тип text [ note: 'Салат/суп/второе...']
}

Table Склад {
	id_продукта integer [ pk increment not null unique ]
	Количество в наличии integer
	Дата date
	Тип склада text [ note: 'Холодильник, морозильник, обычный...']
}

Table Блюда и ингридиенты {
	id_рецепта integer [ pk not null ]
	id_продукта integer [ increment not null unique ]
	Количество продукта integer
	id_блюда integer [ not null ]
	Способ приготовления text
}

Table Поставки {
	id_накладной integer [ pk increment not null unique ]
	Количество integer [ not null ]
	Дата привоза date
	Дата истечения срока годности date [ not null ]
	id_поставщика integer
	id_продукта integer
}

Table Поставщики {
	id_поставщика integer [ pk increment not null unique ]
	Имя text
}

Table Чеки {
	id_чека integer [ pk increment not null unique ]
	Дата date
	Время time
	id_официанта integer
	Сумма чека real
	id_клиента integer
	Тип оплаты text
}

Table Сотрудники {
	id_сотрудника integer [ pk increment not null unique ]
	Должность text
	ФИО text
	Стаж smallint
	Номер телефона bigint
}

Table Продажи {
	id_продажи integer [ pk ]
	id_блюда integer
	id_повара integer
	Дата date
	id_чека integer [ increment not null unique ]
	Сумма продажи real
}

Table Аллергены {
	id_аллергена integer [ pk increment not null unique ]
	Аллерген text
	id_продукта integer
}

Table Клиент {
	id_клиента integer [ pk increment not null unique ]
	Уровень скидок smallint
}

Ref fk_Блюда и ингридиенты_id_блюда_Блюда {
	Блюда и ингридиенты.id_блюда - Блюда.id_блюда [ delete: no action, on update: no action ]
}

Ref fk_Блюда и ингридиенты_id_продукта_Склад {
	Блюда и ингридиенты.id_продукта - Склад.id_продукта [ delete: no action, on update: no action ]
}

Ref fk_Поставки_id_поставщика_Поставщики {
	Поставки.id_поставщика - Поставщики.id_поставщика [ delete: no action, on update: no action ]
}

Ref fk_Поставки_id_продукта_Склад {
	Поставки.id_продукта - Склад.id_продукта [ delete: no action, on update: no action ]
}

Ref fk_Сотрудники_id_сотрудника_Чеки {
	Сотрудники.id_сотрудника - Чеки.id_официанта [ delete: no action, on update: no action ]
}

Ref fk_Продажи_id_чека_Чеки {
	Продажи.id_чека - Чеки.id_чека [ delete: no action, on update: no action ]
}

Ref fk_Продажи_id_блюда_Блюда {
	Продажи.id_блюда - Блюда.id_блюда [ delete: no action, on update: no action ]
}

Ref fk_Продажи_id_повара_Сотрудники {
	Продажи.id_повара - Сотрудники.id_сотрудника [ delete: no action, on update: no action ]
}

Ref fk_Аллергены_id_ингридиента_Блюда и ингридиенты {
	Аллергены.id_продукта - Блюда и ингридиенты.id_продукта [ delete: no action, on update: no action ]
}

Ref fk_Чеки_id_клиента_Клиент {
	Чеки.id_клиента - Клиент.id_клиента [ delete: no action, on update: no action ]
}
